### PR TITLE
Volleyball Activity

### PR DESCRIPTION
**Pull request by Ashish0077**
initial implementation in kotlin
-Tap on Team Name to edit them
-Tap on Scores to increment them
-score required to win a set = 25
-set required to win a match = 3
-switch sides feature is also implemented

Screenshot_1575293652

Signed-off-by: Ashish0077 <ashish007722@gmail.com>

### CODE REVIEW

**Comment by Ashish0077** [comment]
This PR is in response to issue #8

**Comment by chanmol1999** [comment]
Why did you implemented in kotlin?
It should be in java.

**Comment by Ashish0077** [comment]
Since kotlin is the preferred language for the Android development and it is completely interoperable with java. So if someone even wants to use kotlin code from java they can call kotlin code or visa versa

**Comment by Ashish0077** [comment]
This will introduce new language to the code base.  And may also encourage other students to explore kotlin for Android Development. @chanmol1999

**Comment by chanmol1999** [comment]
Although Kotlin is preferred but Java is being used in the project as it is more easy to understand.And  also it is not a good practice if one class suddenly uses another language when all other classes of the project are still in Java.
So @Ashish0077 Although You have done good work but still it is not possible to merge the files written in kotlin .Kindly change them to Java language.

**Comment by Ashish0077** [comment]
please refer to PR #15

**Pull request closed without merging**
