### PR TITLE
PR from Sarthak2601

### LINKED ISSUE #28: Implement Badminton Activity
- [ ] Create a UI for the page
- [ ] Implement functional features for badminton game

### PR DESCRIPTION
**Pull request by Sarthak2601**
Fixes #28 

*UI for Badminton Activity added. 
*Functioning of Badminton activity. 

Screenshot_2019-12-09-20-18-21-855_com example anmol courtcounter
Screenshot_2019-12-09-20-27-35-832_com example anmol courtcounter

### CODE REVIEW

**Review by chanmol1999 — CHANGES_REQUESTED** [review]
Don't use hardcode values. Instead use resources for them.

**Comment by chanmol1999** [comment]
Also use better commit message.
Go through this once: https://chris.beams.io/posts/git-commit/

**Comment by Sarthak2601** [comment]
@chanmol1999 Can I fix these hardcoded ones in the next commit ?  
Also, okay for the commit message one.

**Comment by chanmol1999** [comment]
> @chanmol1999 Can I fix these hardcoded ones in the next commit ?
> Also, okay for the commit message one.

Sure you can do that.

**Comment by Sarthak2601** [comment]
@chanmol1999 next commit as in the next PR I will update everything. For right now please merge this.

**Pull request merged**
