### PR TITLE
initial implementation of volleyball activity

### PR DESCRIPTION
**Pull request by Ashish0077**
-Tap on Team Name to edit them
-Tap on Scores to increment them
-score required to win a set = 25
-set required to win a match = 3
-switch sides feature is also implemented

Signed-off-by: Ashish0077 <ashish007722@gmail.com>

### CODE REVIEW

**Comment by Ashish0077** [comment]
this is in response to issue #8

**Review by chanmol1999 — CHANGES_REQUESTED** [review]
Remove changes in .idea files.
Also include a gif of the functioning of the volleyball activity.

**Comment by Ashish0077** [comment]
score

**Comment by Ashish0077** [comment]
@chanmol1999 
idea files removed and gif is uploaded!!

**Review by chanmol1999 — APPROVED** [review]

**Pull request merged**
